version: '3'

networks: 
    laravel:


services: 
    nginx:
        image: nginx:stable-alpine
        command: nginx -g "daemon off;"
        container_name: nginx 
        ports: 
            - "8080:80"
        volumes:
            - ./src/guwudang.in-backend/public:/var/www/html/public
            - ./nginx:/etc/nginx/conf.d
        depends_on: 
            - php
            - mysql
        networks: 
            - laravel

    mysql:
        image: mysql:5.7.31
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports: 
            - "3306:3306"
        volumes: 
            - mysql-data:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravel
        
    php:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes: 
            - ./src/guwudang.in-backend:/var/www/html
        ports: 
            - "9000:9000"
        networks: 
            - laravel
volumes: 
    mysql-data:
        driver: local