version: '3'

networks: 
    guwudangin:
        name : guwudangin


services: 
    mysql:
        image: mysql:5.7.31
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports: 
            - "3307:3306"
        volumes: 
            - ./mysql:/docker-entrypoint-initdb.d
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - guwudangin

    php:
        image: izzatbey/app-guwudangin:1.5
        container_name: php
        working_dir: /var/www/html
        ports: 
            - "8080:80"
        networks: 
            - guwudangin